services:
  minio:
    image: docker.io/bitnami/minio:2023
    ports:
      - '9110:9000'
      - '9111:9001'
    environment:
      - MINIO_ROOT_USER=abobusamogus
      - MINIO_ROOT_PASSWORD=darkmagapatriot
      - MINIO_DEFAULT_BUCKETS=models
    volumes:
      - './data/minio:/bitnami/minio/data'

  mlflow-postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mlflow_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # mainapp:
  #   image: docker.io/orson88/mlops:main
  #   ports:
  #     - '8181:8080'

volumes:
  minio_data:
    driver: local
  mlflow_postgres_data:
    driver: local