apiVersion: v1
kind: Pod
metadata:
  name: minio
spec:
  containers:
  - name: minio
    image: minio/minio
    args:
    - "server"
    - "/data"
    env:
    - name: MINIO_ACCESS_KEY
      value: "minio"
    - name: MINIO_SECRET_KEY
      value: "minio123"
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    emptyDir: {}